### PR TITLE
Make keys work with tags

### PR DESCRIPTION
**Pull request by micwehrle**
Based on #22 by https://github.com/starsy.
Requires https://github.com/etsy/statsd/pull/539 for statsd

### CODE REVIEW

**Comment by johndodev** [comment]
bump ?

**Comment by johndodev** [comment]
Actually you don't need https://github.com/etsy/statsd/pull/539 since the option `keyNameSanitize: false` do the job.

:+1:

**Comment by SigbertUCE** [comment]
Hi Johndodev..I have Graphite as a backend when sending StatsD metrics from my application.We moved to influxdb 0.10 version and am unable to get the tags working with StatsD.
Eg: When trying to send the below counter in influxdb i see it as a single series name instead of multiple tags.             statsdClient.increment("CCRCBusinessUsage.QuoteCreation.CreateQuote.CreateQuoteBasicClickTestInflux10,service=payroll,region=us-west");

Can you help me identify if StatsD with Graphite does not support multiple tags ?

Sigbert

**Comment by johndodev** [comment]
Hi,

sorry I dont' use Graphite at all, I don't know if the visualizator of graphite support tags.

Anyway, to send tags in influxDb with statsd you can use this fork of influxdb-backend: https://github.com/johndodev/statsd-influxdb-backend

and add `keyNameSanitize: false` in config.js of statsd.

Below is my config: 

```
{
    influxdb: {
        host: '127.0.0.1', // InfluxDB host. (default 127.0.0.1)
        port: 8086, // InfluxDB port. (default 8086)
    version: 0.9,  
        database: 'statsd',  // InfluxDB database instance. (required)
        username: '[username]', // InfluxDB database username. (required)
        password: '[password]', // InfluxDB database password. (required)
        flush: {
            enable: true // Enable regular flush strategy. (default true)
        },
        proxy: {
            enable: false, // Enable the proxy strategy. (default false)
            suffix: 'raw', // Metric name suffix. (default 'raw')
            flushInterval: 1000 // Flush interval for the internal buffer.
                // (default 1000)
        }
    },
    keyNameSanitize: false,
    port: 8125, // StatsD port.
    backends: ['./backends/console', 'statsd-influxdb-backend'],
    debug: false,
    legacyNamespace: false,
    flushInterval: 10000
}
```

**Pull request closed without merging**
